# Тема “Вычисления с помощью Numpy”

## Задание1

In [1]:
import numpy as np

In [13]:
a = np.array([[1, 6], [2, 8], [3,11], [3,10], [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

## Задание 2


In [16]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [23]:
a_c_1 = a_centered[:, 0]
a_c_2 = a_centered[:, 1]
a_centered_sp =a_c_1.dot(a_c_2)
res = a_centered_sp/4
res

2.0

## Задание 4

In [19]:
a_t = a.T
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [24]:
cov = np.cov(a_t)[0][1]
cov

2.0

# Тема “Работа с данными в Pandas”

## Задание 1

In [25]:
import pandas as pd

In [29]:
 authors = pd.DataFrame({'author_id':[1, 2, 3],
                         'author_name':['Тургенев', 'Чехов', 'Островский']})
 authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [30]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                        'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                       'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [32]:
 authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner' )
authors_price 

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [33]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [51]:
author_1 = authors_price.loc[authors_price ['author_id'] == 1]
author_1

author_id author_name         book_title  price
0          1    Тургенев        Отцы и дети    450
1          1    Тургенев              Рудин    300
2          1    Тургенев  Дворянское гнездо    350

In [43]:
author_2 = authors_price.loc[authors_price ['author_id'] == 2]
author_2

author_id author_name        book_title  price
3          2       Чехов  Толстый и тонкий    500
4          2       Чехов   Дама с собачкой    450

In [53]:
author_3 = authors_price.loc[authors_price ['author_id'] == 3]
author_3

author_id author_name            book_title  price
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [54]:
authors_stat = pd.DataFrame({'author_name': ['Тургенев', 'Чехов', 'Островский'],
                'min_price': [author_1['price'].min(),author_2['price'].min(), author_3['price'].min()],
                'max_price': [author_1['price'].max(),author_2['price'].max(), author_3['price'].max()],
                'mean_price':[author_1['price'].mean(),author_2['price'].mean(), author_3['price'].mean()]})
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000